version: '3.8'

services:
  parking-db:
    image: mysql:8
    container_name: parking-db-hub
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: parkinglot
      MYSQL_USER: parkinguser
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"

  parking-app:
    image: duvangt/juan-sosa:v1.0
    container_name: parking-app-hub
    env_file:
      - .env
    ports:
      - "1222:1222"
    depends_on:
      - parking-db