name: Pipeline CI-CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ETAPA 1: Application Build

      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      # i. Compilar la app Java
      - name: Compilar con Maven (sin pruebas)
        run: mvn clean package -DskipTests

      # ii. Copiar el binario resultante (esto se hace en el Dockerfile)
      # iii. Publicar ese binario como artefacto del pipeline
      - name: Publicar .jar como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: parkinglot-jar
          path: target/parkinglot-0.0.1-SNAPSHOT.jar

      # ETAPA 2: Construcción y despliegue del contenedor

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      # iii. Subir la imagen al Container Registry
      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # i. Construir imagen Docker / ii. Taggear la imagen
      - name: Construir y subir imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: duvangt/juan-sosa:v1.0
